
function initCountdown(targetDate){const t=new Date(targetDate).getTime();function u(){const n=Date.now(),d=t-n,ids=['days','hours','mins','secs'];if(d<0){ids.forEach(id=>{const e=document.getElementById(id);if(e)e.textContent='0'});return}const v=[Math.floor(d/86400000),Math.floor((d%86400000)/3600000),Math.floor((d%3600000)/60000),Math.floor((d%60000)/1000)];ids.forEach((id,i)=>{const e=document.getElementById(id);if(e)e.textContent=v[i]})}u();setInterval(u,1000)}
function askConcierge(){const i=document.getElementById('conciergeInput'),f=document.getElementById('conciergeFeed');if(!i||!f)return;const t=i.value.trim();if(!t)return;const u=document.createElement('div');u.className='msg user';u.textContent=t;f.appendChild(u);const b=document.createElement('div');b.className='msg bot';b.textContent=reply(t);f.appendChild(b);i.value='';f.scrollTop=f.scrollHeight}
function reply(t){t=t.toLowerCase();if(t.includes('vip'))return 'VIP is imagined as a prestige social zone with cabanas, hosted circles, and elevated viewing.';if(t.includes('ticket'))return 'This launch build avoids prices. Start with waitlist, reveal dates, and application-led access.';if(t.includes('ride'))return 'The ride district combines skyline visuals, thrill attractions, carnival games, and photo moments.';if(t.includes('food'))return 'Food Village is built as a premium Accra night-market trail with global flavor.';if(t.includes('instagram'))return 'The official Instagram on the site is @alivfest.';return 'ALIV Concierge can guide guests to VIP, rides, games, lineup, waitlist, and contact. Replace this demo later with a real AI assistant.'}
function scrollCarousel(id,dir){const e=document.getElementById(id);if(e)e.scrollBy({left:dir*320,behavior:'smooth'})}
function openWaitlist(){const e=document.getElementById('waitlistModal');if(e)e.classList.add('show')}
function closeWaitlist(){const e=document.getElementById('waitlistModal');if(e)e.classList.remove('show')}
function submitWaitlist(ev){ev.preventDefault();const name=document.getElementById('wlName').value.trim(),email=document.getElementById('wlEmail').value.trim(),city=document.getElementById('wlCity').value.trim(),s=document.getElementById('wlStatus');if(!email){if(s)s.textContent='Please enter an email address.';return}const items=JSON.parse(localStorage.getItem('alivfest_waitlist')||'[]');items.push({name,email,city,createdAt:new Date().toISOString()});localStorage.setItem('alivfest_waitlist',JSON.stringify(items));if(s)s.textContent='Saved locally for demo. Connect this to your real form or email workflow next.'}
window.addEventListener('load',()=>setTimeout(openWaitlist,1200))
